#!/bin/sh

# Based on https://ghost.org/changelog/prevent-master-push/

# Exit codes:
# 0: push
# 1: don't push

protected_branches=('hidden' 'drafts')
current_branch=$(git symbolic-ref HEAD | sed -e 's,.*/\(.*\),\1,')

for (( i=0; i<${#protected_branches[*]}; i++ )) ; do
    if [[ ${protected_branches[i]} == $current_branch ]]
    then
        prompt=$(echo "You're about to push ${protected_branches[i]},"\
                        "is that what you intended?  [y|n] ")
        read -p "${prompt}" -n 1 -r </dev/tty
        echo
        if echo $REPLY | grep -E '^[Yy]$' >/dev/null
        then
            exit 0
        fi
        exit 1
    else
        exit 0
    fi
done
